# TODO: this doesn't produce something that can compile boost.
FROM alpine:3.8
LABEL maintainer="Gary Ritzer <gwritz@gmail.com>"
LABEL version="1.0"

RUN apk add --update boost-dev clang clang-static g++
